services:
  loki:
    image: grafana/loki:3.5.7
    container_name: loki
    command: -config.file=/etc/loki/config.yaml
    restart: unless-stopped
    volumes:
      - ./config/loki.yaml:/etc/loki/config.yaml:ro
      - data_loki:/loki
    # ports:
    #   - "3100:3100"
    labels:
      - "traefik.enable=true"

      # HTTP → HTTPS redirect
      - "traefik.http.routers.loki-http.rule=Host(`loki.anganba.me`)"
      - "traefik.http.routers.loki-http.entrypoints=web"
      - "traefik.http.routers.loki-http.middlewares=redirect-to-https"

      # HTTPS router
      - "traefik.http.routers.loki-https.rule=Host(`loki.anganba.me`)"
      - "traefik.http.routers.loki-https.entrypoints=websecure"
      - "traefik.http.routers.loki-https.tls=true"
      - "traefik.http.routers.loki-https.tls.certresolver=${PROVIDER}"
      - "traefik.http.routers.loki-https.service=loki-svc"
      #- "traefik.http.routers.loki-https.middlewares=redirect-to-https,loki-auth"

      # Basic Auth middleware
      #- "traefik.http.middlewares.loki-auth.basicauth.users=admin:$$apr1$$0ffrmlNf$$eE7DQwp7fdTvFc65a7wMk/"

      # Point Traefik to Loki’s internal port
      - "traefik.http.services.loki-svc.loadbalancer.server.port=3100"

      # Redirect middleware definition
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"


    networks:
      - frontend
      - monitoring

volumes:
  data_loki:

networks:
  frontend:
    external: true
  monitoring:
    external: true
