services:
  loki:
    image: grafana/loki:3.5.7
    container_name: loki
    command: -config.file=/etc/loki/config.yaml
    restart: unless-stopped
    volumes:
      - ./config/loki.yaml:/etc/loki/config.yaml:ro
      - data_loki:/loki
    # ports:
    #   - "3100:3100"
    labels:
      - traefik.enable=true

      # HTTP redirect to HTTPS
      - "traefik.http.routers.loki-http.rule=Host(`loki.anganba.me`)"
      - "traefik.http.routers.loki-http.entrypoints=web"
      - "traefik.http.routers.loki-http.middlewares=redirect-to-https"

      # HTTPS router
      - "traefik.http.routers.loki-https.rule=Host(`loki.anganba.me`)"
      - "traefik.http.routers.loki-https.entrypoints=websecure"
      - "traefik.http.routers.loki-https.tls=true"
      - "traefik.http.routers.loki-https.tls.certresolver=${PROVIDER}"

      # Tell Traefik to connect to Loki’s HTTP port (3100)
      - "traefik.http.services.loki.loadbalancer.server.port=3100"

      # Redirect middleware
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
    networks:
      - frontend
      - monitoring

volumes:
  data_loki:

networks:
  frontend:
    external: true
  monitoring:
    external: true
