global:
  scrape_interval: 15s           # Default: scrape targets every 15 seconds
  evaluation_interval: 15s       # How often to evaluate rules
  scrape_timeout: 10s            # Timeout for scraping a target

  # Optional: labels added to all metrics for identification
  external_labels:
    monitor: 'zenexcloud-monitor'

# -------------------------------------------------------------------
# Alerting (optional) — can be integrated later with Alertmanager
# -------------------------------------------------------------------
# alerting:
#   alertmanagers:
#     - static_configs:
#         - targets:
#             - 'alertmanager:9093'

# -------------------------------------------------------------------
# Scrape configurations
# -------------------------------------------------------------------
scrape_configs:

  # 1️⃣ Prometheus itself
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']

  # 2️⃣ Node Exporter (example host metrics)
  - job_name: 'node_exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  # 3️⃣ cAdvisor (container metrics)
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

  # 4️⃣ Traefik metrics (optional)
  # If you have Traefik metrics enabled on :8082
  # Add this in your Traefik container:
  # command:
  #   - "--metrics.prometheus=true"
  #   - "--metrics.prometheus.addrouterslabels=true"
  #   - "--metrics.prometheus.entryPoint=metrics"
  #
  # Then expose port 8082 and scrape it here:
  - job_name: 'traefik'
    metrics_path: /metrics
    static_configs:
      - targets: ['traefik:8082']

# -------------------------------------------------------------------
# Optional: Federation, remote_write, remote_read can be added later
# -------------------------------------------------------------------
# remote_write:
#   - url: "http://remote-storage:1234/write"
# remote_read:
#   - url: "http://remote-storage:1234/read"
