volumes:
  grafana-data:
    driver: local

services:
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=changeme
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_SERVER_HTTP_ADDR=0.0.0.0
      - GF_SERVER_HTTP_PORT=3000

    volumes:
      - grafana-data:/var/lib/grafana

    restart: unless-stopped
    networks:
      - frontend
      - monitoring

    labels:
      - "traefik.enable=true"

      # ===============================================================
      # 🌍 HTTP Router (handled automatically by Traefik redirect)
      # ===============================================================
      - "traefik.http.routers.grafana.rule=Host(`mon.${DOMAIN}`)"
      - "traefik.http.routers.grafana.entrypoints=web"

      # ===============================================================
      # 🔒 HTTPS Secure Router
      # ===============================================================
      - "traefik.http.routers.grafana-secure.rule=Host(`mon.${DOMAIN}`)"
      - "traefik.http.routers.grafana-secure.entrypoints=websecure"
      - "traefik.http.routers.grafana-secure.tls.certresolver=${PROVIDER}"
      - "traefik.http.routers.grafana-secure.service=grafana-svc"

      # 👤 Optional Basic Auth (if you want to secure Grafana login page)
      # - "traefik.http.middlewares.grafana-auth.basicauth.users=admin:${TRAEFIK_PASSWORD}"
      # - "traefik.http.routers.grafana-secure.middlewares=grafana-auth,secure-headers@docker"

      # 🧩 Apply global secure-headers middleware
      - "traefik.http.routers.grafana-secure.middlewares=secure-headers@docker"

      # ===============================================================
      # ⚙️ Service Definition
      # ===============================================================
      - "traefik.http.services.grafana-svc.loadbalancer.server.port=3000"

networks:
  frontend:
    external: true
  monitoring:
    external: true
