volumes:
  grafana-data:
    driver: local

services:
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=changeme
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_SERVER_HTTP_ADDR=0.0.0.0
      - GF_SERVER_HTTP_PORT=3000

    # ports:
    #   - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
      
    restart: unless-stopped
    networks:
      - frontend
      - monitoring
    labels:
      - "traefik.enable=true"

      # 1. MIDDLEWARE DEFINITION
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.permanent=true"

      # 2. HTTP router 
      - "traefik.http.routers.grafana.rule=Host(\"mon.${DOMAIN}\")"
      - "traefik.http.routers.grafana.entrypoints=web"
      - "traefik.http.routers.grafana.middlewares=redirect-to-https"


      - "traefik.http.routers.grafana-secure.rule=Host(\"mon.${DOMAIN}\")"
      - "traefik.http.routers.grafana-secure.entrypoints=websecure"
      - "traefik.http.routers.grafana-secure.tls=true"
      - "traefik.http.routers.grafana-secure.tls.certresolver=${PROVIDER}"
      - "traefik.http.routers.grafana-secure.service=grafana-svc"

      # 4. Internal port mapping
      - "traefik.http.services.grafana-svc.loadbalancer.server.port=3000"

networks:
  frontend:
    external: true
  monitoring:
    external: true
