services:
  cadvisor:
    image: google/cadvisor:latest
    container_name: cadvisor
    ports:
      - "8085:8080"   # Changed host port -> container port
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro 
      - /var/lib/docker/:/var/lib/docker:ro
    restart: unless-stopped
    networks:
      - frontend
    labels:
      - "traefik.enable=false"

networks:
  frontend:
    external: true
