{
 "title": "Live Server Monitor Overview - R&D",
 "description": "R&D phase of this custom Dashboard",
 "tags": [
  "Prometheus",
  "node_exporter",
  "Anganba",
  "Alloy",
  "Loki",
  "ZenexCloud"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "vendor",
    "query": {
     "query": "label_values(node_uname_info, vendor)"
    }
   },
   {
    "name": "account",
    "query": {
     "query": "label_values(node_uname_info{vendor=~\"$vendor\"}, account)"
    }
   },
   {
    "name": "group",
    "query": {
     "query": "label_values(node_uname_info{vendor=~\"$vendor\",account=~\"$account\"},group)"
    }
   },
   {
    "name": "name",
    "query": {
     "query": "label_values(node_uname_info{vendor=~\"$vendor\",account=~\"$account\",group=~\"$group\"},name)"
    }
   },
   {
    "name": "instance",
    "label": "IP",
    "query": {
     "query": "label_values(node_uname_info{vendor=~\"$vendor\",account=~\"$account\",group=~\"$group\",name=~\"$name\"},instance)"
    }
   },
   { "name": "interval", "query": "3m" },
   {
    "name": "total",
    "label": "Host",
    "query": {
     "query": "query_result(count(node_uname_info{vendor=~\"$vendor\",account=~\"$account\",group=~\"$group\",name=~\"$name\",name=~\".*$sname.*\"}))"
    }
   },
   {
    "name": "device",
    "query": {
     "query": "label_values(node_network_info{vendor=~\"$vendor\",account=~\"$account\",group=~\"$group\",name=~\"$name\",instance=~\"$instance\",device!~'tap.*|veth.*|br.*|docker.*|virbr.*|lo.*|cni.*'},device)"
    }
   },
   {
    "name": "maxmount",
    "query": {
     "query": "query_result(topk(1,sort_desc (max(node_filesystem_size_bytes{vendor=~\"$vendor\",account=~\"$account\",group=~\"$group\",name=~\"$name\",instance=~\"$instance\",fstype=~\"ext.?|xfs\",mountpoint!~\".*pods.*\"}) by (mountpoint))))"
    }
   },
   {
    "name": "show_name",
    "label": "Display",
    "query": {
     "query": "label_values(node_uname_info{vendor=~\"$vendor\",account=~\"$account\",group=~\"$group\",name=~\"$name\",instance=~\"$instance\"}, name)"
    }
   },
   {
    "name": "iid",
    "label": "InstanceID",
    "query": {
     "query": "label_values(node_uname_info{vendor=~\"$vendor\",account=~\"$account\",group=~\"$group\",name=~\"$name\"},iid)"
    }
   },
   { "name": "sname" },
   { "name": "job", "label": "job", "query": { "query": "label_values(job)" } }
  ]
 },
 "panels": [
  {
   "title": "🏡 Resource Overview: Currently Selected Host: $show_name, Instance: $instance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "Server Resource Overview Table【Group：$group，Total Hosts：$total】",
   "type": "table",
   "description": "PartitionUsage、Disk、Disk、DownloadBandwidth、UploadBandwidth, Partition, CollectionUsagePartition。\n\nConnections: CurrEstab - Status ESTABLISHED  CLOSE-WAIT  TCP Connections。\n\nHealthAddedMetrics, CPU, Memory, IO, 90DescriptionSystemResources, TestingMetrics, ParameterOptimization。",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "node_uname_info{vendor=~\"$vendor\",account=~\"$account\",group=~\"$group\",name=~\"$name\",name=~\".*$sname.*\"} - 0",
     "legendFormat": "Host"
    },
    {
     "expr": "sum(time() - node_boot_time_seconds{vendor=~\"$vendor\",account=~\"$account\",group=~\"$group\",name=~\"$name\",name=~\".*$sname.*\"})by(instance)/86400",
     "legendFormat": "Runtime"
    },
    {
     "expr": "node_memory_MemTotal_bytes{vendor=~\"$vendor\",account=~\"$account\",group=~\"$group\",name=~\"$name\",name=~\".*$sname.*\"} - 0",
     "legendFormat": "TotalMemory"
    },
    {
     "expr": "count(node_cpu_seconds_total{vendor=~\"$vendor\",account=~\"$account\",group=~\"$group\",name=~\"$name\",mode='system',name=~\".*$sname.*\"}) by (instance)",
     "legendFormat": "Total"
    },
    {
     "expr": "node_load5{vendor=~\"$vendor\",account=~\"$account\",group=~\"$group\",name=~\"$name\",name=~\".*$sname.*\"}",
     "legendFormat": "5MinuteLoad"
    },
    {
     "expr": "(1 - avg(irate(node_cpu_seconds_total{vendor=~\"$vendor\",account=~\"$account\",group=~\"$group\",name=~\"$name\",mode=\"idle\",name=~\".*$sname.*\"}[$interval])) by (instance)) * 100",
     "legendFormat": "CPU Usage"
    },
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes{vendor=~\"$vendor\",account=~\"$account\",group=~\"$group\",name=~\"$name\",name=~\".*$sname.*\"} / (node_memory_MemTotal_bytes{vendor=~\"$vendor\",account=~\"$account\",group=~\"$group\",name=~\"$name\",name=~\".*$sname.*\"})))* 100",
     "legendFormat": "MemoryUsage"
    },
    {
     "expr": "max((node_filesystem_size_bytes{vendor=~\"$vendor\",account=~\"$account\",group=~\"$group\",name=~\"$name\",name=~\".*$sname.*\",fstype=~\"ext.?|xfs\"}-node_filesystem_free_bytes{vendor=~\"$vendor\",account=~\"$account\",group=~\"$group\",name=~\"$name\",name=~\".*$sname.*\",fstype=~\"ext.?|xfs\"}) *100/(node_filesystem_avail_bytes {vendor=~\"$vendor\",account=~\"$account\",group=~\"$group\",name=~\"$name\",name=~\".*$sname.*\",fstype=~\"ext.?|xfs\"}+(node_filesystem_size_bytes{vendor=~\"$vendor\",account=~\"$account\",group=~\"$group\",name=~\"$name\",name=~\".*$sname.*\",fstype=~\"ext.?|xfs\"}-node_filesystem_free_bytes{vendor=~\"$vendor\",account=~\"$account\",group=~\"$group\",name=~\"$name\",name=~\".*$sname.*\",fstype=~\"ext.?|xfs\"})))by(instance)",
     "legendFormat": "PartitionUsage"
    },
    {
     "expr": "max(irate(node_disk_read_bytes_total{vendor=~\"$vendor\",account=~\"$account\",group=~\"$group\",name=~\"$name\",name=~\".*$sname.*\"}[$interval])) by (instance)"
    },
    {
     "expr": "max(irate(node_disk_written_bytes_total{vendor=~\"$vendor\",account=~\"$account\",group=~\"$group\",name=~\"$name\",name=~\".*$sname.*\"}[$interval])) by (instance)"
    },
    {
     "expr": "node_netstat_Tcp_CurrEstab{vendor=~\"$vendor\",account=~\"$account\",group=~\"$group\",name=~\"$name\",name=~\".*$sname.*\"} - 0",
     "legendFormat": "Connections"
    },
    {
     "expr": "node_sockstat_TCP_tw{vendor=~\"$vendor\",account=~\"$account\",group=~\"$group\",name=~\"$name\",name=~\".*$sname.*\"} - 0",
     "legendFormat": "TIME_WAIT"
    },
    {
     "expr": "max(irate(node_network_receive_bytes_total{vendor=~\"$vendor\",account=~\"$account\",group=~\"$group\",name=~\"$name\",name=~\".*$sname.*\"}[$interval])*8) by (instance)",
     "legendFormat": "DownloadBandwidth"
    },
    {
     "expr": "max(irate(node_network_transmit_bytes_total{vendor=~\"$vendor\",account=~\"$account\",group=~\"$group\",name=~\"$name\",name=~\".*$sname.*\"}[$interval])*8) by (instance)",
     "legendFormat": "UploadBandwidth"
    },
    {
     "expr": "((1-(1 - avg(irate(node_cpu_seconds_total{vendor=~\"$vendor\",account=~\"$account\",group=~\"$group\",name=~\"$name\",name=~\".*$sname.*\",mode=\"idle\"}[$interval])) by (instance))^1.3)^(1/3)*0.5 + \r\n(1-(1 - avg(node_memory_MemAvailable_bytes{vendor=~\"$vendor\",account=~\"$account\",group=~\"$group\",name=~\"$name\",name=~\".*$sname.*\"} / node_memory_MemTotal_bytes{vendor=~\"$vendor\",account=~\"$account\",group=~\"$group\",name=~\"$name\",name=~\".*$sname.*\"})by (instance))^6)^(1/3)*0.3 + \r\n(1 - max(irate(node_disk_io_time_seconds_total{vendor=~\"$vendor\",account=~\"$account\",group=~\"$group\",name=~\"$name\",name=~\".*$sname.*\"}[$interval]))by (instance)^1.1)^(1/2)*0.2)*100",
     "legendFormat": "HealthScore"
    },
    {
     "expr": "max(irate(node_disk_io_time_seconds_total{vendor=~\"$vendor\",account=~\"$account\",group=~\"$group\",name=~\"$name\",name=~\".*$sname.*\"}[$interval])) by (instance) *100",
     "legendFormat": "IOutilUsage"
    }
   ]
  },
  {
   "title": "P99  Usage",
   "type": "table",
   "description": "- P99: Data, 99Data。 (99%Data)\n- Prometheus (Download)\n- Collection1HourData\n- Time Range[7d:1h] 7 DayHourData。\nThis panel calculates and displays the 99th percentile CPU and memory usage (P99) for each instance over the past 7 days, using Prometheus data — helping identify peak resource usage trends.",
   "gridPos": { "h": 7, "w": 2, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "node_uname_info{vendor=~\"$vendor\",account=~\"$account\",group=~\"$group\",name=~\"$name\",name=~\".*$sname.*\"} - 0",
     "legendFormat": "Host"
    },
    {
     "expr": "quantile_over_time(0.99, cpu:usage:rate1m{vendor=~\"$vendor\",account=~\"$account\",group=~\"$group\",name=~\"$name\",name=~\".*$sname.*\"}[7d:1h])",
     "legendFormat": "CPUUsageP99"
    },
    {
     "expr": "quantile_over_time(0.99, mem:usage:rate1m{vendor=~\"$vendor\",account=~\"$account\",group=~\"$group\",name=~\"$name\",name=~\".*$sname.*\"}[7d:1h])",
     "legendFormat": "MemoryUsageP99"
    }
   ]
  },
  {
   "title": "Node IP Mapping",
   "type": "table",
   "description": "Shows hostname and corresponding IP address (from Prometheus labels)\n",
   "gridPos": { "h": 7, "w": 4, "x": 2, "y": 8 },
   "targets": [
    {
     "expr": "node_uname_info{ip_address!=\"\"}\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Overall CPU Usage | $instance",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(node_load5{vendor=~\"$vendor\",account=~\"$account\",group=~\"$group\",name=~\".*$sname.*\",instance=\"$instance\",name=~\"$name\"})",
     "legendFormat": "5mLoad"
    },
    {
     "expr": "count(node_cpu_seconds_total{vendor=~\"$vendor\",account=~\"$account\",group=~\"$group\",name=~\"$name\",name=~\".*$sname.*\",instance=\"$instance\",mode='system'})"
    },
    {
     "expr": "avg(1 - avg(irate(node_cpu_seconds_total{vendor=~\"$vendor\",account=~\"$account\",group=~\"$group\",name=~\"$name\",name=~\".*$sname.*\",instance=\"$instance\",mode=\"idle\"}[$interval])) by (instance)) * 100",
     "legendFormat": "Average%"
    }
   ]
  },
  {
   "title": "Overall Memory Usage | $instance",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes{vendor=~\"$vendor\",account=~\"$account\",group=~\"$group\",instance=\"$instance\",name=~\"$name\",name=~\".*$sname.*\"} - node_memory_MemAvailable_bytes{vendor=~\"$vendor\",account=~\"$account\",group=~\"$group\",instance=\"$instance\",name=~\"$name\",name=~\".*$sname.*\"})",
     "legendFormat": "TotalUsed"
    },
    {
     "expr": "sum(node_memory_MemTotal_bytes{vendor=~\"$vendor\",account=~\"$account\",group=~\"$group\",instance=\"$instance\",name=~\"$name\",name=~\".*$sname.*\"})",
     "legendFormat": "TotalMemory"
    },
    {
     "expr": "(sum(node_memory_MemTotal_bytes{vendor=~\"$vendor\",account=~\"$account\",group=~\"$group\",instance=\"$instance\",name=~\"$name\",name=~\".*$sname.*\"} - node_memory_MemAvailable_bytes{vendor=~\"$vendor\",account=~\"$account\",group=~\"$group\",instance=\"$instance\",name=~\"$name\",name=~\".*$sname.*\"}) / sum(node_memory_MemTotal_bytes{vendor=~\"$vendor\",account=~\"$account\",group=~\"$group\",instance=\"$instance\",name=~\"$name\",name=~\".*$sname.*\"}))*100",
     "legendFormat": "TotalAverage%"
    }
   ]
  },
  {
   "title": "Overall Disk Usage | $instance",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(avg(node_filesystem_size_bytes{vendor=~\"$vendor\",account=~\"$account\",group=~\"$group\",instance=\"$instance\",name=~\"$name\",name=~\".*$sname.*\",fstype=~\"xfs|ext.*\"})by(device,instance)) - sum(avg(node_filesystem_free_bytes{vendor=~\"$vendor\",account=~\"$account\",group=~\"$group\",instance=\"$instance\",name=~\"$name\",name=~\".*$sname.*\",fstype=~\"xfs|ext.*\"})by(device,instance))",
     "legendFormat": "TotalUsage"
    },
    {
     "expr": "sum(avg(node_filesystem_size_bytes{vendor=~\"$vendor\",account=~\"$account\",group=~\"$group\",instance=\"$instance\",name=~\"$name\",name=~\".*$sname.*\",fstype=~\"xfs|ext.*\"})by(device,instance))",
     "legendFormat": "TotalDisk"
    },
    {
     "expr": "(sum(avg(node_filesystem_size_bytes{vendor=~\"$vendor\",account=~\"$account\",group=~\"$group\",instance=\"$instance\",name=~\"$name\",name=~\".*$sname.*\",fstype=~\"xfs|ext.*\"})by(device,instance)) - sum(avg(node_filesystem_free_bytes{vendor=~\"$vendor\",account=~\"$account\",group=~\"$group\",instance=\"$instance\",name=~\"$name\",name=~\".*$sname.*\",fstype=~\"xfs|ext.*\"})by(device,instance))) *100/(sum(avg(node_filesystem_avail_bytes{vendor=~\"$vendor\",account=~\"$account\",group=~\"$group\",instance=\"$instance\",name=~\"$name\",name=~\".*$sname.*\",fstype=~\"xfs|ext.*\"})by(device,instance))+(sum(avg(node_filesystem_size_bytes{vendor=~\"$vendor\",account=~\"$account\",group=~\"$group\",instance=\"$instance\",name=~\"$name\",name=~\".*$sname.*\",fstype=~\"xfs|ext.*\"})by(device,instance)) - sum(avg(node_filesystem_free_bytes{vendor=~\"$vendor\",account=~\"$account\",group=~\"$group\",instance=\"$instance\",name=~\"$name\",name=~\".*$sname.*\",fstype=~\"xfs|ext.*\"})by(device,instance))))",
     "legendFormat": "Average%"
    }
   ]
  },
  {
   "title": "📊 Resource Details: [${show_name}] [${instance}] [${iid}]",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 }
  },
  {
   "title": "[${instance}]: Partition Available Space (EXT.*/XFS/NFS)",
   "type": "table",
   "description": "In this dashboard: the total disk size, used space, available space, and usage rate are consistent with the df command’s Size, Used, Available, and Use% outputs.",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{instance=~\"$instance\",fstype=~\"ext.*|xfs|nfs\",mountpoint !~\".*pod.*\"}-0",
     "legendFormat": "Total"
    },
    {
     "expr": "node_filesystem_avail_bytes {instance=~\"$instance\",fstype=~\"ext.*|xfs|nfs\",mountpoint !~\".*pod.*\"}-0"
    },
    {
     "expr": "(node_filesystem_size_bytes{instance=~\"$instance\",fstype=~\"ext.*|xfs|nfs\",mountpoint !~\".*pod.*\"}-node_filesystem_free_bytes{instance=~\"$instance\",fstype=~\"ext.*|xfs|nfs\",mountpoint !~\".*pod.*\"}) *100/(node_filesystem_avail_bytes {instance=~\"$instance\",fstype=~\"ext.*|xfs|nfs\",mountpoint !~\".*pod.*\"}+(node_filesystem_size_bytes{instance=~\"$instance\",fstype=~\"ext.*|xfs|nfs\",mountpoint !~\".*pod.*\"}-node_filesystem_free_bytes{instance=~\"$instance\",fstype=~\"ext.*|xfs|nfs\",mountpoint !~\".*pod.*\"}))"
    }
   ]
  },
  {
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{instance=~\"$instance\",mode=\"idle\"}[$interval])) * 100)",
     "legendFormat": "TotalCPUUsage"
    },
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes{instance=~\"$instance\"} / (node_memory_MemTotal_bytes{instance=~\"$instance\"})))* 100",
     "legendFormat": "MemoryUsage"
    },
    {
     "expr": "(node_filesystem_size_bytes{instance=~\"$instance\",fstype=~\"ext.*|xfs\",mountpoint=\"$maxmount\"}-node_filesystem_free_bytes{instance=~\"$instance\",fstype=~\"ext.*|xfs\",mountpoint=\"$maxmount\"})*100 /(node_filesystem_avail_bytes {instance=~\"$instance\",fstype=~\"ext.*|xfs\",mountpoint=\"$maxmount\"}+(node_filesystem_size_bytes{instance=~\"$instance\",fstype=~\"ext.*|xfs\",mountpoint=\"$maxmount\"}-node_filesystem_free_bytes{instance=~\"$instance\",fstype=~\"ext.*|xfs\",mountpoint=\"$maxmount\"}))",
     "legendFormat": "Max Disk Space Usage({{mountpoint}})"
    },
    {
     "expr": "(1 - ((node_memory_SwapFree_bytes{instance=~\"$instance\"} + 1)/ (node_memory_SwapTotal_bytes{instance=~\"$instance\"} + 1))) * 100",
     "legendFormat": "PartitionUsage"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "expr": "avg(time() - node_boot_time_seconds{instance=~\"$instance\"})",
     "legendFormat": "Runtime",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    },
    {
     "bucketAggs": [
      { "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "expr": "count(node_cpu_seconds_total{instance=~\"$instance\", mode='system'})",
     "legendFormat": "CPU",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    },
    {
     "bucketAggs": [
      { "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "expr": "sum(node_memory_MemTotal_bytes{instance=~\"$instance\"})",
     "legendFormat": "TotalMemory",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    },
    {
     "bucketAggs": [
      { "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "expr": "avg(irate(node_cpu_seconds_total{instance=~\"$instance\",mode=\"iowait\"}[$interval])) * 100",
     "legendFormat": "CPU iowait",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    },
    {
     "bucketAggs": [
      { "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "expr": "node_filefd_maximum{instance=~\"$instance\"}",
     "legendFormat": "Total",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    },
    {
     "bucketAggs": [
      { "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "expr": "process_max_fds{job=\"node_exporter\",instance=~\"$instance\"}",
     "legendFormat": "Max FDs",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Traffic per Minute: $instance",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "Mibits" } },
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{job=~\"$job\", instance=~\"$instance\", device!~\"lo\"}[$__interval]) * 8 / 1e6\r\n",
     "legendFormat": "{{device}}_download"
    },
    {
     "expr": "rate(node_network_transmit_bytes_total{job=~\"$job\", instance=~\"$instance\", device!~\"lo\"}[$__interval]) * 8 / 1e6\r\n",
     "legendFormat": "{{device}}_upload"
    }
   ]
  },
  {
   "title": "CPU_Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(1 - avg(irate(node_cpu_seconds_total{instance=~\"$instance\",mode=\"idle\"}[$interval])) by (instance))*100",
     "legendFormat": "TotalUsage"
    },
    {
     "expr": "avg(irate(node_cpu_seconds_total{instance=~\"$instance\",mode=\"system\"}[$interval])) by (instance) *100",
     "legendFormat": "SystemUsage"
    },
    {
     "expr": "avg(irate(node_cpu_seconds_total{instance=~\"$instance\",mode=\"user\"}[$interval])) by (instance) *100",
     "legendFormat": "UserUsage"
    },
    {
     "expr": "avg(irate(node_cpu_seconds_total{instance=~\"$instance\",mode=\"iowait\"}[$interval])) by (instance) *100",
     "legendFormat": "DiskIOUsage"
    }
   ]
  },
  {
   "title": "MemoryInformation",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_MemAvailable_bytes{instance=~\"$instance\"}",
     "legendFormat": "Available"
    },
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"$instance\"}",
     "legendFormat": "TotalMemory"
    },
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"$instance\"} - node_memory_MemAvailable_bytes{instance=~\"$instance\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes{instance=~\"$instance\"} / (node_memory_MemTotal_bytes{instance=~\"$instance\"})))* 100",
     "legendFormat": "Usage"
    }
   ]
  },
  {
   "title": "DiskUsage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(node_filesystem_size_bytes{instance=~\"$instance\",fstype=~\"ext.*|xfs|nfs\",mountpoint !~\".*pod.*\"}-node_filesystem_free_bytes{instance=~\"$instance\",fstype=~\"ext.*|xfs|nfs\",mountpoint !~\".*pod.*\"}) *100/(node_filesystem_avail_bytes {instance=~\"$instance\",fstype=~\"ext.*|xfs|nfs\",mountpoint !~\".*pod.*\"}+(node_filesystem_size_bytes{instance=~\"$instance\",fstype=~\"ext.*|xfs|nfs\",mountpoint !~\".*pod.*\"}-node_filesystem_free_bytes{instance=~\"$instance\",fstype=~\"ext.*|xfs|nfs\",mountpoint !~\".*pod.*\"}))",
     "legendFormat": "Capacity %: {{mountpoint}}"
    },
    {
     "expr": "(1 - node_filesystem_files_free{instance=~\"$instance\",fstype=~\"ext.?|xfs|nfs\",mountpoint !~\".*pod.*\"} / node_filesystem_files{instance=~\"$instance\",fstype=~\"ext.?|xfs|nfs\",mountpoint !~\".*pod.*\"}) * 100",
     "legendFormat": "Inodes%：{{mountpoint}}"
    }
   ]
  },
  {
   "title": "SystemAverageLoad",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "node_load1{instance=~\"$instance\"}",
     "legendFormat": "1MinuteLoad"
    },
    {
     "expr": " sum(count(node_cpu_seconds_total{instance=~\"$instance\", mode='system'}) by (cpu,instance)) by(instance)",
     "legendFormat": "CPUTotal"
    },
    {
     "expr": "node_load5{instance=~\"$instance\"}",
     "legendFormat": "5MinuteLoad"
    },
    {
     "expr": "node_load15{instance=~\"$instance\"}",
     "legendFormat": "15MinuteLoad"
    }
   ]
  },
  {
   "title": "RuntimeStatus",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "node_procs_running{instance=~\"$instance\"}",
     "legendFormat": "Runtime",
     "prometheusLink": "/api/datasources/proxy/1/graph#%5B%7B%22expr%22%3A%22node_procs_running%7Binstance%3D%5C%22%24host%5C%22%7D%22%2C%22range_input%22%3A%2243200s%22%2C%22end_input%22%3A%222015-9-18%2013%3A46%22%2C%22step_input%22%3A%22%22%2C%22stacked%22%3Atrue%2C%22tab%22%3A0%7D%5D"
    },
    {
     "calculatedInterval": "2m",
     "expr": "node_procs_blocked{instance=~\"$instance\"}",
     "legendFormat": "IO",
     "prometheusLink": "/api/datasources/proxy/1/graph#%5B%7B%22expr%22%3A%22node_procs_blocked%7Binstance%3D%5C%22%24host%5C%22%7D%22%2C%22range_input%22%3A%2243200s%22%2C%22end_input%22%3A%222015-9-18%2013%3A46%22%2C%22step_input%22%3A%22%22%2C%22stacked%22%3Atrue%2C%22tab%22%3A0%7D%5D"
    }
   ]
  },
  {
   "title": "File Descriptors (FD) / Context Switches per Second",
   "type": "timeseries",
   "description": "It refers to monitoring how many file handles (FDs) a process uses and how many context switches (CPU task swaps) occur each second — both are key indicators of system load and performance.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(node_context_switches_total{instance=~\"$instance\"}[$interval])"
    },
    {
     "expr": "node_filefd_allocated{instance=~\"$instance\"}",
     "legendFormat": "TotalFD"
    },
    {
     "expr": "(node_filefd_allocated{instance=~\"$instance\"}/node_filefd_maximum{instance=~\"$instance\"}) *100",
     "legendFormat": "TotalFD"
    },
    {
     "expr": "(process_open_fds{instance=~\"$instance\"}/process_max_fds{instance=~\"$instance\"}) *100",
     "legendFormat": "FD"
    }
   ]
  },
  {
   "title": "IO (: 100ms)",
   "type": "timeseries",
   "description": "Read time seconds DiskPartition\n\nWrite time seconds DiskPartition\n\nIO time seconds DiskPartition/\n\nIO time weighted secondsDiskPartition/",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "irate(node_disk_read_time_seconds_total{instance=~\"$instance\"}[$interval]) / irate(node_disk_reads_completed_total{instance=~\"$instance\"}[$interval])",
     "legendFormat": "{{device}}_Read"
    },
    {
     "expr": "irate(node_disk_write_time_seconds_total{instance=~\"$instance\"}[$interval]) / irate(node_disk_writes_completed_total{instance=~\"$instance\"}[$interval])",
     "legendFormat": "{{device}}_Write"
    }
   ]
  },
  {
   "title": "DiskRate (IOPS)",
   "type": "timeseries",
   "description": "Reads completed: DiskPartition\n\nWrites completed: DiskPartition\n\nIO now DiskPartition/",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "irate(node_disk_reads_completed_total{instance=~\"$instance\"}[$interval])",
     "legendFormat": "{{device}}_Read"
    },
    {
     "expr": "irate(node_disk_writes_completed_total{instance=~\"$instance\"}[$interval])",
     "legendFormat": "{{device}}_Write"
    }
   ]
  },
  {
   "title": "DiskCapacity",
   "type": "timeseries",
   "description": "Read bytes DiskPartition\nWritten bytes DiskPartition",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "irate(node_disk_read_bytes_total{instance=~\"$instance\"}[$interval])",
     "legendFormat": "{{device}}_Read"
    },
    {
     "expr": "irate(node_disk_written_bytes_total{instance=~\"$instance\"}[$interval])",
     "legendFormat": "{{device}}_Write"
    }
   ]
  },
  {
   "title": "1I/O (I/O Util)",
   "type": "timeseries",
   "description": "每一秒钟的自然时间内，花费在I/O上的耗时。（wall-clock time）\n\nnode_disk_io_time_seconds_total：\n磁盘花费在输入/输出操作上的秒数。该值为累加值。（Milliseconds Spent Doing I/Os）\n\nirate(node_disk_io_time_seconds_total[1m])：\n计算每秒的速率：(last值-last前一个值)/时间戳差值，即：1秒钟内磁盘花费在I/O操作的时间占比。",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "irate(node_disk_io_time_seconds_total{instance=~\"$instance\"}[$interval])",
     "legendFormat": "{{device}}_I/O Operations per Second"
    }
   ]
  },
  {
   "title": "NetworkSocketInformation",
   "type": "timeseries",
   "description": "Sockets_used - Total\n\nCurrEstab - Status ESTABLISHED  CLOSE-WAIT  TCP Connections\n\nTCP_alloc -  (、sk_buff)TCP\n\nTCP_tw - TCPConnections\n\nUDP_inuse -  UDP \n\nRetransSegs - TCP \n\nOutSegs - TCP \n\nInSegs - TCP",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "node_netstat_Tcp_CurrEstab{instance=~\"$instance\"}",
     "legendFormat": "CurrEstab"
    },
    {
     "expr": "node_sockstat_TCP_tw{instance=~\"$instance\"}",
     "legendFormat": "TCP_tw"
    },
    {
     "expr": "node_sockstat_sockets_used{instance=~\"$instance\"}",
     "legendFormat": "Sockets_used"
    },
    {
     "expr": "node_sockstat_UDP_inuse{instance=~\"$instance\"}",
     "legendFormat": "UDP_inuse"
    },
    {
     "expr": "node_sockstat_TCP_alloc{instance=~\"$instance\"}",
     "legendFormat": "TCP_alloc"
    },
    {
     "expr": "irate(node_netstat_Tcp_InSegs{instance=~\"$instance\"}[$interval])",
     "legendFormat": "Tcp_InSegs"
    },
    {
     "expr": "irate(node_netstat_Tcp_OutSegs{instance=~\"$instance\"}[$interval])",
     "legendFormat": "Tcp_OutSegs"
    },
    {
     "expr": "irate(node_netstat_Tcp_RetransSegs{instance=~\"$instance\"}[$interval])",
     "legendFormat": "Tcp_RetransSegs"
    }
   ]
  },
  {
   "title": "Network Bandwidth Usage per Second $device",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{job=~\"$job\", instance=~\"$instance\", device!~\"lo|docker.*|veth.*|br.*|cni.*\"}[30m]) * 8 / 1e6\r\n",
     "legendFormat": "{{device}}_Download"
    },
    {
     "expr": "rate(node_network_transmit_bytes_total{job=~\"$job\", instance=~\"$instance\", device!~\"lo|docker.*|veth.*|br.*|cni.*\"}[30m]) * 8 / 1e6\r\n",
     "legendFormat": "{{device}}_Upload"
    }
   ]
  },
  { "title": "Loki Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 54 } },
  {
   "title": "Loki RAW Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 55 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{job=\"loki\"}"
    }
   ]
  },
  {
   "title": "SSH Error Logs | $instance",
   "type": "logs",
   "gridPos": { "h": 8, "w": 13, "x": 0, "y": 63 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{job=\"security\", app=\"auth\", instance=\"$instance\"} |= \"Failed\""
    }
   ]
  },
  {
   "title": "SSH Accepted Logs | $instance",
   "type": "logs",
   "gridPos": { "h": 8, "w": 11, "x": 13, "y": 63 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{app=\"auth\", job=\"security\", instance=\"$instance\"} |= \"Accepted password\""
    }
   ]
  },
  {
   "title": "Nginx Logs | $instance",
   "type": "logs",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 71 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{job=\"web\", app=\"nginx_access\",instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Auditd Logs",
   "type": "logs",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 78 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{job=\"security\", app=\"auditd\",instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Auditd Logs",
   "type": "logs",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 85 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{job=\"security\", app=\"auditd\",instance=\"$instance\"}"
    }
   ]
  }
 ]
}