server:
  http_listen_port: 9080
  grpc_listen_port: 0

# Use the new persistent volume path
positions:
  filename: /var/promtail/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  # =================================================================
  # JOB 1: Docker Service Discovery (Industry Standard)
  # =================================================================
  - job_name: docker
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s
        # filters:
        #   - name: label
        #     values: ["logging=true"]

    relabel_configs:
      - source_labels: ['__meta_docker_container_host']
        replacement: ${HOSTNAME}
        target_label: host
      
      - source_labels: ['__meta_docker_container_name']
        regex: '/(.*)'
        target_label: job
        
      - source_labels: ['__meta_docker_container_name']
        regex: '/(.*)'
        target_label: container
        
      - source_labels: ['__meta_docker_container_image_name']
        target_label: image
        
      - source_labels: ['__meta_docker_container_log_stream']
        target_label: stream

    pipeline_stages:
      - docker: {}

      - json:
          expressions:
            level: level
            msg: msg | message | log
            service: service | app
            time: time | timestamp | "@timestamp"

      - labels:
          level:
          service:
          
      
      - timestamp:
          source: time
          format: RFC3339Nano
          
      - output:
          source: msg

  # =================================================================
  # JOB 2: Host System Logs
  # =================================================================
  - job_name: system
    static_configs:
      - targets:
          - localhost
        labels:
          job: system
          host: ${HOSTNAME}
          __path__: /var/log/{syslog,auth.log,kern.log,*.log}