services:
  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    command:
      - --path.procfs=/host/proc
      - --path.sysfs=/host/sys
      - --path.rootfs=/rootfs
      - --collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($$|/) # <-- The fix is here
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro,rslave
    restart: unless-stopped
    networks:
      - frontend

networks:
  frontend:
    external: true