services:
  tempo:
    image: grafana/tempo:2.4.1
    container_name: tempo
    command: -config.file=/etc/tempo/config.yaml
    restart: unless-stopped
    volumes:
      - ./config/tempo.yaml:/etc/tempo/config.yaml:ro
      - tempo_data:/tmp/tempo
    labels:
      - traefik.enable=true
      # --- Traefik Router ---
      - traefik.http.routers.tempo.rule=Host(`tempo.alo.anganba.me`)
      - traefik.http.routers.tempo.entrypoints=websecure
      - traefik.http.routers.tempo.tls=true
      - traefik.http.routers.tempo.tls.certresolver=${PROVIDER}
      - traefik.http.routers.tempo.service=tempo
      # --- Traefik Service ---
      - traefik.http.services.tempo.loadbalancer.server.port=3200
    networks:
      - frontend
      - monitoring

volumes:
  tempo_data:

networks:
  frontend:
    external: true
  monitoring:
    external: true
