services:
  tempo:
    image: grafana/tempo:2.4.1
    container_name: tempo
    command: -config.file=/etc/tempo/config.yaml
    restart: unless-stopped
    volumes:
      - ./config/tempo.yaml:/etc/tempo/config.yaml:ro
      - tempo_data:/tmp/tempo
    labels:
      # --- This is your EXISTING Grafana API router ---
      - "traefik.enable=true"
      - "traefik.http.routers.tempo.rule=Host(\"tempo.${DOMAIN}\")"
      - "traefik.http.routers.tempo.entrypoints=websecure"
      - "traefik.http.routers.tempo.tls=true"
      - "traefik.http.routers.tempo.tls.certresolver=${PROVIDER}"
      - "traefik.http.services.tempo.loadbalancer.server.port=3200"

      # --- ADD THESE LABELS for OTLP HTTP Ingestion ---
      # Create a new router for OTLP, maybe on a subdomain or path
      - "traefik.http.routers.tempo-otlp-http.rule=Host(\"tempo-otlp.${DOMAIN}\")"
      - "traefik.http.routers.tempo-otlp-http.entrypoints=websecure"
      - "traefik.http.routers.tempo-otlp-http.tls=true"
      - "traefik.http.routers.tempo-otlp-http.tls.certresolver=${PROVIDER}"
      - "traefik.http.services.tempo-otlp-http.loadbalancer.server.port=4318"
    networks:
      - frontend
      - monitoring

volumes:
  tempo_data:

networks:
  frontend:
    external: true
  monitoring:
    external: true
